################################################################################
substitutions:
  device_name: garage-multi-sensor
  device_id: garage_multi_sensor
  device_friendly_name: Garage Multi Sensor
  device_sampling_time: 30s
  ld24_tx: GPIO43
  ld24_rx: GPIO44
  bme280_sda: GPIO08
  bme280_scl: GPIO09
  bh1750_sda: GPIO10
  bh1750_scl: GPIO11  # flip SCL & SCA Pins

packages:
  multi-sensor: github://schettada/esphome/esp32_multi_sensor_bluetooth_proxy.yaml
  sensors: github://schettada/esphome/sensors.yaml
  buttons: github://schettada/esphome/buttons.yaml
  
esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false

api:
  encryption:
    key: "NkqPORUAn7U1w2BUbM+abVJquCKuG+04+7fKV0HLXaI="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True
  
esp32_ble_tracker:
  scan_parameters:
    active: false

bluetooth_proxy:
  active: false
 