################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_name: s3-matrix
  device_id: s3_matrix
  device_friendly_name: S3 Matrix
  device_sampling_time: 30s
  gpio_pin: GPIO14
  num_leds: 64
  rgb_order: RGB

packages:
  bluetooth-proxy: github://schettada/esphome/esp32-generic-s3.yaml@main
  sensors: github://schettada/esphome/sensors.yaml@main
  buttons: github://schettada/esphome/buttons.yaml@main
  lights: github://schettada/esphome/lights.yaml@main

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1

# Enable Home Assistant API
api:
  encryption:
    key: "bUbTV9SpnPdGFRs8CHiQ3oV3ES7EMyTr8e1iUpBZnJA="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True